project_id = "lwbmtirzntexaxdlhgsk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[edge_runtime]
enabled = true
port = 54329

[functions]
verify_jwt = true

[functions.delete-today-dismissal]
verify_jwt = true

[functions.complete-mode]
verify_jwt = true

[functions.complete-today-run-if-timeout]
verify_jwt = true

[functions.dismissal-scheduler]
verify_jwt = false

[functions.end-mode-session]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.notify-first-school-user]
verify_jwt = false

[functions.complete-oauth-profile]
verify_jwt = true

[functions.link-oauth-to-invitation]
verify_jwt = true