export const brandColors = {
  navyDeep: '#011576',
  blueBright: '#0184F7',
  gray50: '#f3f4f6',
  gray700: '#374151',
  gray500: '#6B7280',
  grayBorder: '#E5E7EB',
  codeBackground: '#f4f4f4',
  codeBorder: '#eee',
  redDanger: '#DC2626',
  redBackground: '#FEF2F2',
  blueInfo: '#0184F7',
  blueInfoBackground: '#F0F9FF',
  greenSuccess: '#10B981',
  // Aliases for easier reference
  primary: '#0184F7',
  danger: '#DC2626',
  success: '#10B981',
  info: '#0184F7',
  textSecondary: '#6B7280',
  border: '#E5E7EB',
};

export const fontFamily = "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";

export const styles = {
  main: {
    backgroundColor: brandColors.gray50,
    padding: '40px 20px',
  },
  container: {
    backgroundColor: '#ffffff',
    margin: '0 auto',
    padding: '40px',
    borderRadius: '8px',
    maxWidth: '600px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  logoContainer: {
    backgroundColor: '#ffffff',
    padding: '30px',
    textAlign: 'center' as const,
    borderRadius: '8px 8px 0 0',
    marginBottom: '30px',
  },
  h1: {
    color: brandColors.blueBright,
    fontSize: '28px',
    fontWeight: '600',
    margin: '0',
    fontFamily,
  },
  text: {
    color: brandColors.gray700,
    fontSize: '16px',
    lineHeight: '24px',
    margin: '0 0 20px',
    fontFamily,
  },
  button: {
    backgroundColor: brandColors.navyDeep,
    borderRadius: '6px',
    color: '#ffffff',
    display: 'inline-block',
    fontSize: '16px',
    fontWeight: '600',
    padding: '14px 40px',
    textDecoration: 'none',
    textAlign: 'center' as const,
    margin: '20px 0',
    fontFamily,
    width: 'auto',
    maxWidth: '100%',
    whiteSpace: 'normal' as const,
    wordBreak: 'break-word' as const,
  },
  code: {
    display: 'inline-block',
    padding: '16px',
    width: '100%',
    backgroundColor: brandColors.codeBackground,
    borderRadius: '5px',
    border: `1px solid ${brandColors.codeBorder}`,
    color: '#333',
    fontSize: '18px',
    textAlign: 'center' as const,
    fontFamily: 'monospace',
    margin: '10px 0 20px',
  },
  footerText: {
    color: brandColors.gray500,
    fontSize: '14px',
    lineHeight: '20px',
    margin: '20px 0',
    fontFamily,
  },
  footer: {
    color: brandColors.gray500,
    fontSize: '14px',
    lineHeight: '20px',
    marginTop: '30px',
    paddingTop: '20px',
    borderTop: `1px solid ${brandColors.grayBorder}`,
    fontFamily,
  },
  securityNote: {
    color: brandColors.redDanger,
    fontSize: '14px',
    lineHeight: '20px',
    margin: '20px 0',
    padding: '15px',
    backgroundColor: brandColors.redBackground,
    borderRadius: '6px',
    borderLeft: `4px solid ${brandColors.redDanger}`,
    fontFamily,
  },
  infoNote: {
    color: brandColors.blueInfo,
    fontSize: '14px',
    lineHeight: '20px',
    margin: '20px 0',
    padding: '15px',
    backgroundColor: brandColors.blueInfoBackground,
    borderRadius: '6px',
    borderLeft: `4px solid ${brandColors.blueInfo}`,
    fontFamily,
  },
};
