// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwbmtirzntexaxdlhgsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3Ym10aXJ6bnRleGF4ZGxoZ3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTIzMTgsImV4cCI6MjA2OTc2ODMxOH0.6spEfXtZjS1qGGzJHoyphcAGpdF9_OwOFZdw6fYP_FE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});